[package]
name = "committy"
version = "0.1.0"
authors = ["Arnaud (Martient) Leherpeur <arnaud.leherpeur@taultek.com>"]
edition = "2021"
description = "🚀 Generate clear, concise, and structured commit messages effortlessly"
repository = "https://github.com/martient/committy"
license-file = "LICENSE"
include = ["/src", "LICENSE"]



[dependencies]
structopt = "0.3"
inquire = "0.7.5"
git2 = "0.19.0"
thiserror = "1.0.64"
anyhow = "1.0"
sentry = "0.34.0"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.0"
tempfile = "3.13.0"