name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: rustfmt, clippy
    - name: Check formatting
      run: cargo fmt -- --check
    - name: Lint with clippy
      run: cargo clippy -- -D warnings
    - name: Run tests
      run: cargo test

  tag:
    needs: lint-and-test
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Create new release tag
      uses: martient/git-version-manager@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_API_TAGGING: true
        WITH_V: true
        PRERELEASE: false