name: Release

on:
  release:
    types: [created, prereleased, released]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: cargo build --release
    - name: List target/release contents
      run: ls -l target/release
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: committy
        path: target/release/committy

  release:
    permissions:
      contents: write
      discussions: write
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: committy
    
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            committy